'use strict';
const orderCardNote='Товар под заказ. Цвет уточняйте по наличию. Надписи можно любые. Упаковка – по наличию; по вашему желанию ее можно заменить на другую';
const businessCardNote='Метраж рассчитывается индивидуально для каждого заказчика. Цена зависит от объема работы.';
const stockAwareAdd=add;
add=function(id){const p=allProducts.find(p=>p.id===id);if(!p?.madeToOrder)return stockAwareAdd(id);cart[id]=(cart[id]||0)+1;updateCounts();cartToast();if(modalMode==='cart')showCart()};
function compactPhotos(p){return productPhotos({...p,images:p.images||[]})}
function compactActions(p,basket=false){return basket?`<div class="quantity"><button data-qty="${p.id}" data-delta="-1" aria-label="Уменьшить количество">−</button><span>${cart[p.id]}</span><button data-qty="${p.id}" data-delta="1" aria-label="Увеличить количество">+</button><button data-remove="${p.id}" aria-label="Удалить товар">×</button></div>`:`<div class="product-actions">${p.business?`<button class="primary" data-form="${esc(businessRequest(p,0))}">Обсудить оформление</button>`:`<button class="primary" data-add="${p.id}" ${p.stock===0?'disabled':''}>${p.stock===0?'Нет в наличии':'В корзину'}</button>`}</div>`}
card=function(p,mode=false){return `<article class="product-card compact-card ${p.business?'business-card':p.madeToOrder?'balloon-bouquet-card':''}">${compactPhotos(p)}<div class="product-info" data-info-product="${p.id}"><h3><button data-detail="${p.id}">${displayName(p)}</button></h3><button class="product-more" data-detail="${p.id}">${p.business?'Подробнее об оформлении на фото':'Подробнее о товаре'}</button>${p.business?`<p class="product-note">${businessCardNote}</p>`:p.madeToOrder?`<p class="product-note">${orderCardNote}</p>`:stockMarkup(p)}<strong class="product-price">${displayPrice(p)}</strong>${compactActions(p,mode==='cart')}</div></article>`};
businessCard=p=>card(p);
detail=function(id,index=0){const p=allProducts.find(p=>p.id===id);if(!p)return;openModal(`<article class="product-detail compact-detail ${p.business?'business-card':''}"><h2 class="modal-title">${displayName(p)}</h2>${compactPhotos(p)}${p.business?`${p.description?`<p>${esc(p.description)}</p>`:''}<p>${esc(p.note||'')}</p><p>${businessCardNote}</p><p class="business-photo-price">${esc(businessPhotoPrice(p,index))}</p>`:`${p.slug?productComposition(p):'<p>Состав уточните у флориста.</p>'}<p>${esc(productNote({...p,description:p.description||''}))}</p>${p.madeToOrder?`<p>${orderCardNote}</p>`:''}<p>Наличие, детали заказа и окончательную стоимость подтвердит флорист.</p>`}${stockMarkup(p)}<strong class="product-price">${displayPrice(p)}</strong>${compactActions(p)}</article>`,'detail');if(index&&p.images?.length)moveProductPhoto($('#modalBody .live-photo'),index)};
// The entire description opens details; nested cart/quantity controls keep their own actions.
document.addEventListener('click',event=>{const info=event.target.closest('[data-info-product]');if(!info||event.target.closest('button,a,input,select,textarea'))return;const frame=info.closest('article').querySelector('.live-photo');detail(info.dataset.infoProduct,Number(frame?.dataset.photoIndex||0))});
document.addEventListener('click',event=>{const b=event.target.closest('.compact-card [data-detail]');if(!b)return;event.preventDefault();event.stopImmediatePropagation();const frame=b.closest('article').querySelector('.live-photo');detail(b.dataset.detail,Number(frame?.dataset.photoIndex||0))},true);
// Keep content compact and align matching cards across the whole section.
alignBusinessCards=function(){};
function alignCompactCards(){document.querySelectorAll('.product-grid').forEach(grid=>{const cards=[...grid.querySelectorAll(':scope > .compact-card')];cards.forEach(c=>[...c.querySelector('.product-info').children].forEach(el=>el.style.removeProperty('min-height')));const rows=new Map();cards.forEach(c=>{const top=c.classList.contains('business-card')?'business':c.classList.contains('balloon-bouquet-card')?'balloons':'flowers';if(!rows.has(top))rows.set(top,[]);rows.get(top).push(c)});rows.forEach(row=>{for(let i=0;i<4;i++){const cells=row.map(c=>c.querySelector('.product-info').children[i]);const height=Math.ceil(Math.max(...cells.map(el=>el.getBoundingClientRect().height)));cells.forEach(el=>el.style.minHeight=height+'px')}})})}
let compactFrame;function scheduleCompact(){cancelAnimationFrame(compactFrame);compactFrame=requestAnimationFrame(alignCompactCards)}
new MutationObserver(scheduleCompact).observe(document.querySelector('main'),{childList:true,subtree:true});
new MutationObserver(scheduleCompact).observe($('#modalBody'),{childList:true,subtree:true});
window.addEventListener('resize',scheduleCompact);document.fonts.ready.then(scheduleCompact);
document.addEventListener('click',event=>{const asset=event.target.closest('[data-stationery]');if(!asset)return;openModal(`<h2 class="modal-title">${esc(asset.dataset.title)}</h2><img class="stationery-full" src="${asset.dataset.stationery}" alt="${esc(asset.dataset.title)}"><a class="outline" href="${asset.dataset.stationery}" download>Скачать изображение</a>`,'stationery')});
const renderFlowerCatalog=render;
render=function(){renderFlowerCatalog();const daily=allProducts.find(p=>p.category==='Букет дня');const target=$('#dailyOffer');if(target){target.innerHTML=daily?card(daily):'';polishPhotos();scheduleCompact()}};
render();renderBalloonCatalog();scheduleCompact();
