'use strict';
const simpleNavigation=[['Все','#directions'],['Цветы','#catalog'],['Воздушные шары','#balloons'],['Подарочный сертификат','#certificate'],['Помочь с выбором','#quiz']];
$('#mega').innerHTML=simpleNavigation.map(([name,url])=>`<a href="${url}">${name}</a>`).join('');$('#mega').addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()});
$('#benefits').innerHTML=[["Цветы + шары в одном заказе","Подберём шары в цвет вашего букета."],["Под любой бюджет","От небольшого букета до большого праздничного заказа."],["Соберём индивидуально","Можем собрать по вашему пожеланию"],["Гарантируем качество","Гарантия от 3 дней. Если цветы завяли из-за их качества, несмотря на соблюдение наших рекомендаций по уходу, мы обязательно решим проблему"],["Закажем нужный цветок специально для вас","Если его сейчас нет в наличии"],["Предзаказ по фиксированной цене","Согласуем состав и условия до оплаты."],["Доставка","По городу бесплатно при заказе от 5 000 ₽. Время и адрес согласуем заранее."],["Фото перед отправкой","Вы увидите подарок до его вручения."]].map(([title,body])=>`<article><span aria-hidden="true">♥</span><h3>${title}</h3><p>${body}</p></article>`).join('');
const reviews=[['Анжела С.','Не раз заказываю букеты в этом цветочном магазине – и всегда в полном восторге! Цветы свежие, бутоны упругие, а оттенки – именно такие, как на фото. Особенно впечатляет работа флориста: композиции получаются очень гармоничные, с продуманными деталями – чувствуется настоящий профессионализм.\nРекомендую! Спасибо за красоту и заботу о клиентах! 😊'],['nik.larionof','Отличный сервис. Беру лилии здесь уже 5 месяцев. Качество цветов превосходное. Букет стоит от 2 до 3 недель. Благодарю за качественный товар!!!'],['ash1omy','Приятная атмосфера и замечательные букеты. Персонал отзывчивый и дружелюбный. Флорист Анастасия – самая лучшая!\nВсем советую это прекрасное место🥰'],['Юлия Александрова','Муж дарит цветы от этого магазина ! Очень нравится что долго стоят)'],['Алена С.','Вежливый персонал. Безумно красивые букеты. Рекомендую 👍🏼']];
$('#reviewTrack').innerHTML=reviews.map(([name,body])=>`<article class="customer-review"><div class="review-author"><span class="review-avatar" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"/><path d="M5 21v-3a7 7 0 0 1 14 0v3"/></svg></span><h3>${esc(name)}</h3><span class="review-stars" aria-label="5 из 5 звёзд">★★★★★</span></div><p>${esc(body).replaceAll('\n','<br>')}</p></article>`).join('');
// Annual graduation countdown to May 20 in Perm; the card omits the date.
const calendarHolidays=holidays;
holidays=function(now=new Date()){const events=calendarHolidays(now);const year=Number(permDate(now).slice(0,4));const target=y=>new Date(y+'-05-20T00:00:00+05:00');let graduation=target(year);if(now>=new Date(+graduation+86400000))graduation=target(year+1);events.push({name:'Выпускной',target:graduation,days:Math.max(0,Math.ceil((graduation-now)/86400000))});return events.sort((a,b)=>a.target-b.target)};
let holidaySignature='';
renderHolidays=function(){const events=holidays(),signature=JSON.stringify(events);if(signature===holidaySignature)return;holidaySignature=signature;const oldScroll=$('#holidayGrid').scrollLeft;$('#holidayGrid').innerHTML=events.map(h=>`<article class="holiday">${h.name==='Выпускной'?'':`<span class="eyebrow">${h.target?h.target.toLocaleDateString('ru-RU',{timeZone:'Asia/Yekaterinburg',day:'numeric',month:'long',year:'numeric'}):'ДАТУ СОГЛАСУЕМ С ВАМИ'}</span>`}<h3>${h.name}</h3><span class="countdown">${h.days===null?'Дата уточняется':h.days===0?'Сегодня':h.days}</span><p>${h.days===null?'Подберём оформление под дату вашего выпускного.':h.days===0?'С праздником! Наличие уточнит флорист.':'дней до праздника'}</p><button class="outline holiday-order" data-form="${h.days===0?'Подарок':'Предзаказ'}: ${h.name}">Выбрать подарок заранее</button></article>`).join('');$('#holidayGrid').scrollLeft=oldScroll;updateCarousel('holidayGrid')};
function updateCarousel(id){const track=$('#'+id);const cards=[...track.children];if(!cards.length)return;const width=cards[0].getBoundingClientRect().width+parseFloat(getComputedStyle(track).gap||0),start=Math.round(track.scrollLeft/width),visible=Math.max(1,Math.round(track.clientWidth/width)),end=Math.min(cards.length,start+visible);$('#'+(id==='reviewTrack'?'reviewPosition':'holidayPosition')).textContent=id==='reviewTrack'?`${start+1} / ${cards.length}`:(visible===1?`${start+1} из ${cards.length}`:`${start+1}–${end} из ${cards.length}`);const prev=$(`[data-slide="${id}"][data-dir="-1"]`),next=$(`[data-slide="${id}"][data-dir="1"]`);prev.disabled=track.scrollLeft<2;next.disabled=track.scrollLeft+track.clientWidth>=track.scrollWidth-2}
for(const id of ['reviewTrack','holidayGrid']){$('#'+id).addEventListener('scroll',()=>updateCarousel(id),{passive:true});new ResizeObserver(()=>updateCarousel(id)).observe($('#'+id))}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-slide]');if(btn){const t=$('#'+btn.dataset.slide);const step=t.children[0].getBoundingClientRect().width+parseFloat(getComputedStyle(t).gap);t.scrollBy({left:Number(btn.dataset.dir)*step,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}});
renderHolidays();setInterval(()=>renderHolidays(),60000);updateCarousel('reviewTrack');
let inlineBalloons=false;
const galleryCard=card;
card=function(p,mode=false){if(mode!==true&&mode!=='cart')return galleryCard(p,false);const inCart=mode==='cart';return `<article class="product-card basket-product"><div class="photo"><span class="camera" aria-hidden="true"></span><button class="heart ${favorites.includes(p.id)?'selected':''}" data-fav="${p.id}" aria-label="${favorites.includes(p.id)?'Убрать из избранного':'В избранное'}" aria-pressed="${favorites.includes(p.id)}">${favorites.includes(p.id)?'♥':'♡'}</button></div><div class="product-info"><h3>${displayName(p)}</h3><p>Состав</p><strong class="product-price">${displayPrice(p)}</strong>${inCart?`<div class="quantity"><button data-qty="${p.id}" data-delta="-1" aria-label="Уменьшить количество">−</button><span>${cart[p.id]}</span><button data-qty="${p.id}" data-delta="1" aria-label="Увеличить количество">+</button><button class="remove-product" data-remove="${p.id}" aria-label="Удалить товар">×</button></div>`:`<button class="primary" data-add="${p.id}">В корзину</button>`}</div></article>`};

balloons=function(){closeModal();$('#balloons').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})};
showCart=function(){const items=allProducts.filter(p=>cart[p.id]);openModal(`<h2 class="modal-title">Ваша корзина</h2>${items.length?`<div class="stack-actions basket-top"><button class="primary" data-form="Заявка на заказ">Оформить заказ</button><button class="outline" data-add-balloons aria-expanded="${inlineBalloons}">Добавить шары</button></div>${productInformation()}<div class="product-grid basket-grid">${items.map(p=>card(p,'cart')).join('')}</div><div class="cart-summary"><strong>Итого: ${cartPrice()}</strong></div><p class="form-note">Окончательную стоимость и доставку согласует флорист. Формы пока не отправляют заявки.</p>`:'<div class="empty"><h3>Здесь пока пусто</h3><p>Выберите подарок в каталоге.</p><button class="primary" data-back-catalog>Перейти в каталог</button></div>'}`,'cart')};
showFavorites=function(){const items=allProducts.filter(p=>favorites.includes(p.id));openModal(`${items.length?`<div class="product-grid basket-grid">${items.map(p=>card(p,true)).join('')}</div>`:'<div class="empty"><h3>Ваши любимые ещё впереди</h3><button class="primary" data-back-catalog>Выбрать букет</button></div>'}`,'favorites')};
$('#cartButton').onclick=()=>{inlineBalloons=false;showCart()};$('#favoritesButton').onclick=()=>{inlineBalloons=false;showFavorites()};
contactButtons=function(){return `<div class="contact-options"><a class="primary" href="tel:+79194936187">Позвонить</a><div class="write-options"><span>Написать:</span><div class="socials">${['MAX','VK'].map(c=>`<button data-social="${c}" aria-label="Написать в ${c==='MAX'?'Макс':'ВК'}">${socialIcon(c)}</button>`).join('')}</div></div></div>`};
showContactOptions=function(){openModal(`<h2 class="modal-title">Спасибо! Ваша заявка отправлена. Мы свяжемся с вами в ближайшее время</h2>${contactButtons()}`,'contacts')};
const originalForm=form;form=function(subject,channel=''){if(subject==='Задать вопрос'||subject==='Помощь флориста'){openModal(`<h2 class="modal-title">Связаться с флористом</h2><p>Ежедневно 10:00–22:00</p>${contactButtons()}`,'contacts');return}originalForm(subject,channel)};
$('#loadMap').onclick=()=>{$('#storeMap').innerHTML='<iframe title="Магазин За цветком: Пермь, ул. Куйбышева, 51" src="https://yandex.ru/map-widget/v1/?ll=56.238462%2C58.001938&z=17&pt=56.238462%2C58.001938%2Cpm2rdm" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe><a class="plain-action map-link" href="https://yandex.ru/maps/?ll=56.238462%2C58.001938&z=17&pt=56.238462%2C58.001938%2Cpm2rdm" target="_blank" rel="noopener">ул. Куйбышева, 51, Пермь – открыть карту ↗</a>'};
// Bare text controls get a glyph-shaped glow and arrow, never a rectangular halo.
function decorateActions(root=document){root.querySelectorAll('.plain-action,.text-button,.similar,#clearPrice,[data-quiz-channel]').forEach(el=>{if(el.closest('header')||el.classList.contains('outline'))return;el.querySelectorAll('span[aria-hidden="true"]').forEach(span=>span.remove());el.textContent=el.textContent.replace(/[↗→]/g,'').trim();el.classList.remove('plain-action','text-button','similar');el.classList.add('outline')})}
decorateActions();new MutationObserver(()=>decorateActions($('#modalBody'))).observe($('#modalBody'),{childList:true,subtree:true});
render();renderBalloonCatalog();
