'use strict';
// Explicit contact configuration. Fill only with this shop's confirmed contacts.
const shopContacts={phone:'+79194936187',MAX:'',VK:''};
const vkIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="1" y="1" width="22" height="22" rx="6" fill="currentColor"/><path fill="#FDEAF1" d="M5.5 7.5h2.2c.2 3.6 1.8 5.1 3 5.4V7.5h2.1v3.1c1.2-.2 2.5-1.7 2.9-3.1h2.1c-.3 1.7-1.7 3.3-2.7 4 1 .5 2.6 1.9 3.2 4h-2.4c-.5-1.4-1.7-2.6-3.1-2.8v2.8h-.3c-4.9 0-7.7-3.4-8-8z"/></svg>';
const socialIcon=c=>c==='MAX'?'<img src="max-icon.svg" alt="" width="28" height="28">':vkIcon;
$$('.socials').forEach(group=>{group.innerHTML=['MAX','VK'].map(c=>`<button data-social="${c}" aria-label="Написать в ${c==='MAX'?'Макс':'ВК'}" title="${c==='MAX'?'Макс':'ВК'}">${socialIcon(c)}</button>`).join('')});
const originalNames=new Map(allProducts.map(p=>[p.id,p.name]));
function displayName(p){return p.category==='Букет дня'?'Букет дня':'Название'}
function displayPrice(p){return p.category==='Букет дня'?money(999):'Цена'}
function cartPrice(){const items=allProducts.filter(p=>cart[p.id]);return items.some(p=>p.category!=='Букет дня')?'Уточнит флорист':money(items.reduce((s,p)=>s+p.price*cart[p.id],0))}
updateCounts=function(){ $('#favCount').textContent=favorites.length;const count=Object.values(cart).reduce((s,n)=>s+n,0);$('#cartTotal').textContent=count?`${count} шт.`:'0';storage.set('cart',cart);storage.set('favorites',favorites)};
card=function(p,favoritesView=false){return `<article class="product-card"><div class="photo"><button class="heart ${favorites.includes(p.id)?'selected':''}" data-fav="${p.id}" aria-label="${favorites.includes(p.id)?'Убрать из избранного':'В избранное'}: ${displayName(p)}" aria-pressed="${favorites.includes(p.id)}">${favorites.includes(p.id)?'♥':'♡'}</button>${p.category==='Букет дня'?'<span class="badge">Букет дня</span>':''}<button class="product-photo-button" data-detail="${p.id}" aria-label="Подробнее: ${displayName(p)}"><span class="camera" aria-hidden="true"></span></button></div><div class="product-info"><h3><button data-detail="${p.id}">${displayName(p)}</button></h3><p>Состав</p><strong class="product-price">${displayPrice(p)}</strong><div class="product-actions"><button class="primary" data-add="${p.id}">В корзину</button><button class="outline" data-similar="${p.id}">Собрать похожий</button>${favoritesView===true?`<button class="outline" data-balloons-for="${p.id}">Добавить шары</button>`:''}</div></div></article>`};
showCart=function(){const items=allProducts.filter(p=>cart[p.id]);openModal(`<h2 class="modal-title">Ваша корзина</h2>${items.length?items.map(p=>`<div class="cart-item"><div><h3>${displayName(p)}</h3><p>${displayPrice(p)}</p></div><div class="quantity"><button data-qty="${p.id}" data-delta="-1" aria-label="Уменьшить количество">−</button><span>${cart[p.id]}</span><button data-qty="${p.id}" data-delta="1" aria-label="Увеличить количество">+</button></div><button data-remove="${p.id}" aria-label="Удалить товар">×</button></div>`).join('')+`<div class="cart-summary"><strong>Итого: ${cartPrice()}</strong></div><div class="stack-actions"><button class="primary" data-form="Заявка на заказ">Оформить заказ</button><button class="outline" data-add-balloons>Добавить шары</button></div><p class="form-note">Стоимость и доставку согласует флорист. В предварительной версии заявки не отправляются.</p>`:'<div class="empty"><h3>Здесь пока пусто</h3><p>Выберите что-нибудь для красивого повода.</p><button class="primary" data-back-catalog>Перейти в каталог</button></div>'}`,'cart')};
showFavorites=function(){modalMode='favorites';openModal(`<h2 class="modal-title">Избранное</h2><p>Сохраняется в этом браузере без регистрации.</p>${favorites.length?`<div class="stack-actions favorites-actions"><button class="primary" data-order-favorites>Оформить избранное</button><button class="outline" data-add-balloons>Добавить шары</button></div><div class="product-grid favorites-grid">${allProducts.filter(p=>favorites.includes(p.id)).map(p=>card(p,true)).join('')}</div>`:'<div class="empty"><h3>Ваши любимые ещё впереди</h3><p>Нажмите на сердечко у понравившегося букета.</p><button class="primary" data-back-catalog>Выбрать букет</button></div>'}`,'favorites')};
detail=function(id){const p=allProducts.find(p=>p.id===id);openModal(`<article class="product-detail"><h2 class="modal-title">${displayName(p)}</h2>${photo}<p>Состав</p><strong>${displayPrice(p)}</strong><div class="stack-actions"><button class="primary" data-add="${id}">В корзину</button><button class="outline" data-similar="${id}">Собрать похожий</button></div></article>`,'detail')};
balloons=function(){openModal(`<h2 class="modal-title">Добавьте шары</h2><p>Флорист подберёт оттенки к вашему букету.</p>${balloonProducts.map(b=>`<div class="cart-item"><div><h3>Название</h3><p>Состав · Цена</p></div><button class="primary" data-add="${b.id}">Добавить</button></div>`).join('')}<button class="outline more" data-open-cart>Перейти в корзину</button>`,'balloon-picker')};
function cartToast(){clearTimeout(toast.timer);$('#toast').innerHTML='<span>Добавлено в корзину</span><button class="toast-go" data-open-cart>Перейти</button>';$('#toast').classList.add('show');toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),7000)}
function contactButtons(){return '<div class="stack-actions contact-options"><button class="primary" data-call>Позвонить</button><button class="outline" data-social="MAX">Написать в Макс</button><button class="outline" data-social="VK">Написать в ВК</button></div>'}
function showContactOptions(){openModal(`<h2 class="modal-title">Выберите удобный способ связи</h2><p class="form-note">Предварительная версия: заявка не отправлена, данные не сохранены. Контакты магазина будут подключены перед началом приёма заказов.</p>${contactButtons()}`,'contacts')}
// Missing contacts are never replaced with contacts from another business.
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if('openCart'in d){$('#toast').classList.remove('show');showCart()}if('addBalloons'in d)balloons();if('orderFavorites'in d){for(const id of favorites){const p=allProducts.find(p=>p.id===id);if(p&&(p.stock===null||p.stock>0)&&!cart[id])cart[id]=1}updateCounts();form('Заявка на заказ')}if('call'in d){if(shopContacts.phone)location.href='tel:'+shopContacts.phone;else openModal('<h2 class="modal-title">Связаться с магазином</h2><p>Номер телефона будет добавлен перед открытием сайта.</p><button class="outline" data-close>Понятно</button>')}if(d.social&&shopContacts[d.social])window.open(shopContacts[d.social],'_blank','noopener');});
let balloonFilter='Все',balloonExpanded=false;

// Demo items use internal prices only to exercise filters; no invented price is displayed.

let balloonPriceMin=0,balloonPriceMax=Infinity;
function renderBalloonCatalog(){const list=balloonGallery.filter(p=>(balloonFilter==='Все'||p.category===balloonFilter)&&p.price>=balloonPriceMin&&p.price<=balloonPriceMax);$('#balloonChips').innerHTML=['Все',...balloonCategories].map(c=>`<button data-balloon="${c}" class="${c===balloonFilter?'active':''}">${c}</button>`).join('');$('#balloonProducts').innerHTML=list.length?list.slice(0,balloonExpanded?99:8).map(card).join(''):'<p class="balloon-empty">'+(balloonGallery.some(p=>balloonFilter==='Все'||p.category===balloonFilter)?'По выбранной цене ничего не найдено. Измените диапазон или сбросьте его.':'Товары в этой категории скоро появятся.')+'</p>';$('#moreBalloons').hidden=list.length<=8;$('#moreBalloons').textContent=balloonExpanded?'Свернуть':'Смотреть все'}
$('#moreBalloons').onclick=()=>{balloonExpanded=!balloonExpanded;renderBalloonCatalog()};
function resetPrices(){priceMin=0;priceMax=Infinity;$('#priceFrom').value='';$('#priceTo').value='';$('#priceError').textContent=''}
$('#priceFilter').onsubmit=e=>{e.preventDefault();const min=Number($('#priceFrom').value||0),max=$('#priceTo').value===''?Infinity:Number($('#priceTo').value);if(min<0||max<0||min>max){$('#priceError').textContent='Сумма «От» должна быть не больше суммы «До».';$('#priceFrom').focus();return}$('#priceError').textContent='';priceMin=min;priceMax=max;expanded=false;render()};$('#clearPrice').onclick=()=>{resetPrices();render()};
$('#cartButton').onclick=showCart;$('#favoritesButton').onclick=showFavorites;
// Do not interrupt a form or another dialog: defer the timed promotion until it closes.
let bonusDue=false,bonusShown=false;function showBonus(){if(!bonusDue||bonusShown||$('#modal').open||document.hidden)return;bonusShown=true;openModal('<span class="eyebrow">ПРИЯТНО ПОЗНАКОМИТЬСЯ</span><h2 class="modal-title">Скидка 300 ₽<br>на первый заказ</h2><p>Ваш первый букет – с приятным знаком внимания. Условия применения скидки уточните у флориста.</p><button class="primary" data-form="Скидка 300 ₽ на первый заказ">Получить скидку</button>','bonus')};setTimeout(()=>{bonusDue=true;showBonus()},10000);$('#modal').addEventListener('close',()=>setTimeout(showBonus,0));document.addEventListener('visibilitychange',showBonus);
const stickyHeader=$('header');new ResizeObserver(()=>document.documentElement.style.setProperty('--header-height',stickyHeader.offsetHeight+'px')).observe(stickyHeader);
render();renderBalloonCatalog();updateCounts();

document.addEventListener('click',e=>{if(e.target.closest('[data-fav]'))renderBalloonCatalog()});
